from enum import StrEnum


class AgentState(StrEnum):
    OFFLINE = "OFFLINE"
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    DIALING = "DIALING"
    CONNECTED = "CONNECTED"
    WRAP_UP = "WRAP_UP"
    PAUSED = "PAUSED"


class CallState(StrEnum):
    QUEUED = "QUEUED"
    RESERVED = "RESERVED"
    INITIATED = "INITIATED"
    RINGING = "RINGING"
    ANSWERED = "ANSWERED"
    CONNECTED = "CONNECTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    ABANDONED = "ABANDONED"


class BorrowerState(StrEnum):
    PENDING = "PENDING"
    LOCKED = "LOCKED"
    IN_CALL = "IN_CALL"
    DONE = "DONE"
    EXHAUSTED = "EXHAUSTED"
    SUPPRESSED = "SUPPRESSED"


class PacingMode(StrEnum):
    PROGRESSIVE = "PROGRESSIVE"
    PREDICTIVE = "PREDICTIVE"


class ReasonCode(StrEnum):
    OK = "OK"
    NO_AGENTS = "NO_AGENTS"
    OVERDIAL_CAP = "OVERDIAL_CAP"
    ABANDON_BUDGET_BREACH = "ABANDON_BUDGET_BREACH"
    PROVIDER_DEGRADED = "PROVIDER_DEGRADED"
    INSUFFICIENT_SAMPLES = "INSUFFICIENT_SAMPLES"
    ESTIMATOR_UNSTABLE = "ESTIMATOR_UNSTABLE"
    RINGING_HARD_CAP = "RINGING_HARD_CAP"
    COOLDOWN_FORCED_PROGRESSIVE = "COOLDOWN_FORCED_PROGRESSIVE"
    CAMPAIGN_PAUSED = "CAMPAIGN_PAUSED"
